# https://taskfile.dev

version: '3'

vars:
  output: "{{.TASKFILE_DIR}}/EmeralEngine-dist"

tasks:
  build:
    args:
      - output
    cmds:
      - git -C "{{.TASKFILE_DIR}}" submodule update --remote
      - task --dir "{{.TASKFILE_DIR}}/runtime" output="{{.output}}/gameruntime"
      - rm "{{.output}}/gameruntime/emeral.h" || true
      - dotnet publish "{{.TASKFILE_DIR}}/engine" -c Release -r win-x64 -p:PublishReadyToRun=true -o "{{.output}}"
    silent: false

  publish:
    args:
      - output
    cmds:
      - task: build
      - strip "{{.output}}/gameruntime/emeral.dll"

  clean:
    args:
      - output
    cmds:
      - dotnet clean "{{.TASKFILE_DIR}}/engine" -c Release
      - rm -r "{{.output}}" || true

  default:
    cmds:
      - task: build